import Ed25519Manager from "../../src/KeyManager/Ed25519Manager";
import VaultysId from "../../src/VaultysId";
import { writeFileSync } from "fs";
import { resolve } from "path";

async function generateTestVectors() {
  console.log("Generating test vectors for Go compatibility...");

  // Fixed entropy for deterministic results
  const entropy = Buffer.from("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", "hex");

  // Generate Ed25519Manager
  const km = await Ed25519Manager.createFromEntropy(entropy);

  // Create VaultysId
  const vid = new VaultysId(km, undefined, 1); // TypePerson = 1

  // Test data for signing
  const message = Buffer.from("test message for compatibility");
  const signature = await km.sign(message);

  // Generate shared secret for DH test
  const bobEntropy = Buffer.from("fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210", "hex");
  const bobKm = await Ed25519Manager.createFromEntropy(bobEntropy);

  // Perform Diffie-Hellman
  const aliceCypher = await km.getCypher();
  const sharedSecret = await aliceCypher.diffieHellman(bobKm.cypher.publicKey);

  // Generate HMAC
  const hmacResult = aliceCypher.hmac("test/endpoint");

  // Challenge signing
  const challenge = {
    version: 1,
    protocol: "test",
    service: "example",
    timestamp: 1234567890,
    nonce: Buffer.from("deadbeefdeadbeefdeadbeefdeadbeef", "hex"),
  };

  const signIncipit = Buffer.from("VAULTYS_SIGN", "utf8");
  const { encode } = await import("@msgpack/msgpack");
  const challengeBytes = Buffer.from(encode(challenge));
  const challengeData = Buffer.concat([signIncipit, challengeBytes]);
  const challengeSignature = await km.sign(challengeData);

  const vectors = {
    description: "Test vectors generated by TypeScript for Go compatibility",
    timestamp: new Date().toISOString(),
    version: "1.0.0",

    keyGeneration: {
      entropy: entropy.toString("hex"),
      ed25519: {
        publicKey: km.signer.publicKey.toString("hex"),
        secretKey: km.signer.secretKey?.toString("hex") || "",
      },
      x25519: {
        publicKey: km.cypher.publicKey.toString("hex"),
        secretKey: km.cypher.secretKey?.toString("hex") || "",
      },
    },

    identity: {
      type: 1, // TypePerson
      did: vid.did,
      idBytes: vid.id.toString("hex"),
      idBytesLength: vid.id.length,
    },

    signing: {
      message: message.toString("hex"),
      messageUtf8: message.toString("utf8"),
      signature: signature.toString("hex"),
    },

    diffieHellman: {
      aliceEntropy: entropy.toString("hex"),
      bobEntropy: bobEntropy.toString("hex"),
      bobPublicKey: bobKm.cypher.publicKey.toString("hex"),
      sharedSecret: sharedSecret.toString("hex"),
    },

    hmac: {
      message: "test/endpoint",
      fullMessage: "VaultysID/test/endpoint/end",
      result: hmacResult?.toString("hex") || "",
    },

    challenge: {
      challengeObject: challenge,
      challengeBytes: challengeBytes.toString("hex"),
      fullDataToSign: challengeData.toString("hex"),
      signature: challengeSignature.toString("hex"),
    },

    serialization: {
      secret: km.getSecret().toString("hex"),
      publicId: km.id.toString("hex"),
    },

    // Additional test cases with different data
    additionalSignatures: [
      {
        message: "",
        signature: (await km.sign(Buffer.from(""))).toString("hex"),
      },
      {
        message: "VaultysID",
        signature: (await km.sign(Buffer.from("VaultysID"))).toString("hex"),
      },
      {
        message: Buffer.from([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).toString("hex"),
        signature: (await km.sign(Buffer.from([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))).toString("hex"),
      },
    ],
  };

  // Write to file
  const outputPath = resolve(__dirname, "test-vectors.json");
  writeFileSync(outputPath, JSON.stringify(vectors, null, 2));

  console.log(`Test vectors written to: ${outputPath}`);
  console.log("\nKey information:");
  console.log(`  Ed25519 Public Key: ${km.signer.publicKey.toString("hex")}`);
  console.log(`  X25519 Public Key: ${km.cypher.publicKey.toString("hex")}`);
  console.log(`  DID: ${vid.did}`);
  console.log(`  ID length: ${vid.id.length} bytes`);

  return vectors;
}

// Export for use in tests
export { generateTestVectors };

// Run if executed directly
if (require.main === module) {
  generateTestVectors()
    .then(() => {
      console.log("\n✅ Test vectors generated successfully");
      process.exit(0);
    })
    .catch((err) => {
      console.error("❌ Error generating test vectors:", err);
      process.exit(1);
    });
}
