/**
 * Saltpack vectors for the Go implementation: ciphertexts produced here by
 * VaultysId.encrypt / signcrypt, which go/test/compatibility/saltpack_ts_test.go
 * must open. Regenerate with:
 *
 *   pnpm tsx test/interops/generate-saltpack-vectors.ts
 *
 * Saltpack encryption is randomized, so the file changes on every run; what
 * the Go test checks is that every ciphertext opens to its plaintext, for every
 * recipient, with the right sender — not byte equality.
 */
import VaultysId from "../../src/VaultysId";
import { createHash } from "crypto";
import { writeFileSync } from "fs";
import { resolve } from "path";

type Alg = "ed25519" | "dilithium";
const MACHINE = 0;
const PERSON = 1;

const entropy = (seed: number) => Buffer.from(Array.from({ length: 32 }, (_, i) => (seed + i) & 0xff));

async function identity(seed: number, type: number, alg: Alg, version: 0 | 1) {
  const vid = (await VaultysId.fromEntropy(entropy(seed), type, alg)).toVersion(version);
  return { vid, export: { secret: vid.getSecret("base64"), alg, version, id: vid.id.toString("hex") } };
}

/**
 * Deterministic text crossing saltpack's 1 MiB chunk boundary: the line below
 * repeated, truncated to 1 MiB + 4 KiB. The Go test rebuilds it the same way.
 */
function large() {
  const line = "VaultysHub stored password · chunk boundary test · ";
  return line.repeat(Math.ceil((1024 * 1024 + 4096) / Buffer.byteLength(line))).slice(0, 1024 * 1024 + 4096);
}

async function main() {
  const ids = {
    // The shapes the server uses: a machine identity, in its v1 and legacy v0 encodings.
    server: await identity(0x10, MACHINE, "ed25519", 1),
    serverV0: await identity(0x30, MACHINE, "ed25519", 0),
    alice: await identity(0x50, PERSON, "ed25519", 1),
    bob: await identity(0x70, PERSON, "ed25519", 1),
    carolPQ: await identity(0x90, PERSON, "dilithium", 1),
  };
  type Name = keyof typeof ids;

  type Case = { name: string; plaintext?: string; plaintextSha256?: string; recipients: Name[]; sender: Name | null; ciphertext: string; expectError?: string };
  const cases: Case[] = [];
  // `storeHash`: keep only the plaintext's SHA-256 (the large case, regenerated by the reader).
  const add = async (name: string, plaintext: string, recipients: Name[], sender: Name | null, storeHash = false) => {
    const recipientIds = recipients.map((r) => ids[r].vid.id);
    const ciphertext = sender ? await ids[sender].vid.signcrypt(plaintext, recipientIds) : await VaultysId.encrypt(plaintext, recipientIds);
    const content = storeHash ? { plaintextSha256: createHash("sha256").update(plaintext, "utf8").digest("hex") } : { plaintext };
    cases.push({ name, ...content, recipients, sender, ciphertext });
  };

  await add("anonymous, one recipient (stored app password)", "s3cr3t-P@ssw0rd!", ["server"], null);
  await add("anonymous, legacy v0 recipient", "legacy organization password", ["serverV0"], null);
  await add("anonymous, three recipients incl. post-quantum", "shared with a folder", ["server", "bob", "carolPQ"], null);
  await add("known sender, two recipients", "signcrypted note", ["bob", "carolPQ"], "alice");
  await add("known post-quantum sender", "from a PQ identity", ["server"], "carolPQ");
  await add("unicode", "mot de passe — ünïcödé 🔐 密码", ["server"], null);
  await add("empty", "", ["server"], null);
  // @vaultys/saltpack emits no payload packet for an empty input, which saltpack
  // v2 forbids (the final packet is what detects truncation): TypeScript itself
  // refuses to open it, and Go must refuse it the same way. Flip this once the
  // fork emits an empty final packet.
  cases[cases.length - 1].expectError = "no payload packet (message truncated)";
  await add("larger than one chunk", large(), ["server"], "alice", true);

  const vectors = {
    description: "VaultysId saltpack ciphertexts produced by TypeScript, to be opened by Go",
    generatedBy: "typescript/test/interops/generate-saltpack-vectors.ts",
    identities: Object.fromEntries(Object.entries(ids).map(([k, v]) => [k, v.export])),
    cases,
  };
  const out = resolve(__dirname, "../../../go/test/compatibility/testdata/saltpack-ts-vectors.json");
  writeFileSync(out, JSON.stringify(vectors, null, 2) + "\n");
  console.log(`wrote ${cases.length} cases to ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
