//go:build ignore
// +build ignore

package main

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/vaultys/vaultysid-go/pkg/keymanager"
	"github.com/vaultys/vaultysid-go/pkg/vaultysid"
	"github.com/vmihailenco/msgpack/v5"
)

type TestVectors struct {
	Description string    `json:"description"`
	Timestamp   time.Time `json:"timestamp"`
	Version     string    `json:"version"`

	KeyGeneration struct {
		Entropy string `json:"entropy"`
		Ed25519 struct {
			PublicKey string `json:"publicKey"`
			SecretKey string `json:"secretKey"`
		} `json:"ed25519"`
		X25519 struct {
			PublicKey string `json:"publicKey"`
			SecretKey string `json:"secretKey"`
		} `json:"x25519"`
	} `json:"keyGeneration"`

	Identity struct {
		Type          int    `json:"type"`
		DID           string `json:"did"`
		IDBytes       string `json:"idBytes"`
		IDBytesLength int    `json:"idBytesLength"`
	} `json:"identity"`

	Signing struct {
		Message     string `json:"message"`
		MessageUTF8 string `json:"messageUtf8"`
		Signature   string `json:"signature"`
	} `json:"signing"`

	DiffieHellman struct {
		AliceEntropy string `json:"aliceEntropy"`
		BobEntropy   string `json:"bobEntropy"`
		BobPublicKey string `json:"bobPublicKey"`
		SharedSecret string `json:"sharedSecret"`
	} `json:"diffieHellman"`

	HMAC struct {
		Message     string `json:"message"`
		FullMessage string `json:"fullMessage"`
		Result      string `json:"result"`
	} `json:"hmac"`

	Challenge struct {
		ChallengeObject interface{} `json:"challengeObject"`
		ChallengeBytes  string      `json:"challengeBytes"`
		FullDataToSign  string      `json:"fullDataToSign"`
		Signature       string      `json:"signature"`
	} `json:"challenge"`

	Serialization struct {
		Secret   string `json:"secret"`
		PublicID string `json:"publicId"`
	} `json:"serialization"`

	AdditionalSignatures []struct {
		Message   string `json:"message"`
		Signature string `json:"signature"`
	} `json:"additionalSignatures"`
}

func main() {
	fmt.Println("Generating test vectors for TypeScript compatibility...")

	// Fixed entropy for deterministic results
	entropyHex := "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	entropy, _ := hex.DecodeString(entropyHex)

	// Generate Ed25519Manager
	km, err := keymanager.CreateFromEntropy(entropy)
	if err != nil {
		panic(err)
	}

	// Create VaultysId
	vid, err := vaultysid.FromEntropy(entropy, vaultysid.TypePerson)
	if err != nil {
		panic(err)
	}

	// Test data for signing
	message := []byte("test message for compatibility")
	signature, err := km.Sign(message)
	if err != nil {
		panic(err)
	}

	// Generate shared secret for DH test
	bobEntropyHex := "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
	bobEntropy, _ := hex.DecodeString(bobEntropyHex)
	bobKm, _ := keymanager.CreateFromEntropy(bobEntropy)

	// Perform Diffie-Hellman
	sharedSecret, err := km.DiffieHellman(bobKm.Cypher.PublicKey)
	if err != nil {
		panic(err)
	}

	// Generate HMAC
	hmacResult, err := km.HMAC("test/endpoint")
	if err != nil {
		panic(err)
	}

	// Challenge signing
	challenge := map[string]interface{}{
		"version":   1,
		"protocol":  "test",
		"service":   "example",
		"timestamp": 1234567890,
		"nonce":     []byte{0xde, 0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef, 0xde, 0xad, 0xbe, 0xef},
	}

	signIncipit := []byte("VAULTYS_SIGN")
	challengeBytes, _ := msgpack.Marshal(challenge)
	challengeData := append(signIncipit, challengeBytes...)
	challengeSignature, _ := km.Sign(challengeData)

	// Additional signatures
	var additionalSigs []struct {
		Message   string `json:"message"`
		Signature string `json:"signature"`
	}

	// Empty message
	sig1, _ := km.Sign([]byte{})
	additionalSigs = append(additionalSigs, struct {
		Message   string `json:"message"`
		Signature string `json:"signature"`
	}{
		Message:   "",
		Signature: hex.EncodeToString(sig1),
	})

	// "VaultysID" message
	sig2, _ := km.Sign([]byte("VaultysID"))
	additionalSigs = append(additionalSigs, struct {
		Message   string `json:"message"`
		Signature string `json:"signature"`
	}{
		Message:   "VaultysID",
		Signature: hex.EncodeToString(sig2),
	})

	// Binary message
	binaryMsg := []byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
	sig3, _ := km.Sign(binaryMsg)
	additionalSigs = append(additionalSigs, struct {
		Message   string `json:"message"`
		Signature string `json:"signature"`
	}{
		Message:   hex.EncodeToString(binaryMsg),
		Signature: hex.EncodeToString(sig3),
	})

	// Get secret
	secret, _ := km.GetSecret()

	// Build test vectors
	vectors := TestVectors{
		Description: "Test vectors generated by Go for TypeScript compatibility",
		Timestamp:   time.Now(),
		Version:     "1.0.0",
	}

	vectors.KeyGeneration.Entropy = entropyHex
	vectors.KeyGeneration.Ed25519.PublicKey = hex.EncodeToString(km.Signer.PublicKey)
	vectors.KeyGeneration.Ed25519.SecretKey = hex.EncodeToString(km.Signer.SecretKey)
	vectors.KeyGeneration.X25519.PublicKey = hex.EncodeToString(km.Cypher.PublicKey)
	vectors.KeyGeneration.X25519.SecretKey = hex.EncodeToString(km.Cypher.SecretKey)

	vectors.Identity.Type = int(vaultysid.TypePerson)
	vectors.Identity.DID = vid.DID()
	vectors.Identity.IDBytes = hex.EncodeToString(vid.ToBytes())
	vectors.Identity.IDBytesLength = len(vid.ToBytes())

	vectors.Signing.Message = hex.EncodeToString(message)
	vectors.Signing.MessageUTF8 = string(message)
	vectors.Signing.Signature = hex.EncodeToString(signature)

	vectors.DiffieHellman.AliceEntropy = entropyHex
	vectors.DiffieHellman.BobEntropy = bobEntropyHex
	vectors.DiffieHellman.BobPublicKey = hex.EncodeToString(bobKm.Cypher.PublicKey)
	vectors.DiffieHellman.SharedSecret = hex.EncodeToString(sharedSecret)

	vectors.HMAC.Message = "test/endpoint"
	vectors.HMAC.FullMessage = "VaultysID/test/endpoint/end"
	vectors.HMAC.Result = hex.EncodeToString(hmacResult)

	vectors.Challenge.ChallengeObject = challenge
	vectors.Challenge.ChallengeBytes = hex.EncodeToString(challengeBytes)
	vectors.Challenge.FullDataToSign = hex.EncodeToString(challengeData)
	vectors.Challenge.Signature = hex.EncodeToString(challengeSignature)

	vectors.Serialization.Secret = hex.EncodeToString(secret)
	vectors.Serialization.PublicID = hex.EncodeToString(km.ToBytes())

	vectors.AdditionalSignatures = additionalSigs

	// Write to file
	outputPath := filepath.Join("test", "compatibility", "go-test-vectors.json")
	data, err := json.MarshalIndent(vectors, "", "  ")
	if err != nil {
		panic(err)
	}

	if err := os.WriteFile(outputPath, data, 0644); err != nil {
		panic(err)
	}

	fmt.Printf("Test vectors written to: %s\n", outputPath)
	fmt.Println("\nKey information:")
	fmt.Printf("  Ed25519 Public Key: %x\n", km.Signer.PublicKey)
	fmt.Printf("  X25519 Public Key: %x\n", km.Cypher.PublicKey)
	fmt.Printf("  DID: %s\n", vid.DID())
	fmt.Printf("  ID length: %d bytes\n", len(vid.ToBytes()))
	fmt.Println("\n✅ Test vectors generated successfully")
}
